const translations = {
    ar: {
        home: {
            title: "استضافة ماينكرافت مجانية",
            subtitle: "الاستضافة هي مهنتنا؛ العملاء السعيد هم الأولوية. نحن نهدف إلى توفير خوادم ماينكرافت الأعلى جودة في السوق باستخدام أحدث التقنيات.",
            button_register: "تسجيل",
            button_dashboard: "لوحة التحكم",
            nav_contact: "التواصل",
            nav_panel: "لوحة التحكم",
            nav_dashboard: "منطقة العلماء",
            nav_button: "تسجيل",
            plans_title: "خططنا",
            plans_subtitle: "تستخدم جميع خوادم استضافة ماينكرافت تخزين SSD من الألف إلى الياء. مع MChost ، يمكنك الاستمتاع بزيادة الأداء والامتثال والتحكم الكامل في الخادم الخاص بك.",
            plan_free_title: "مجاني",
            plan_premium_title: "ممتاز",
            plan_bungee_title: "حزمة Bungee",
            plan_custom_title: "مخصصة",
            plan_free_plugins: "بلوقنات لا نهائية",
            plan_free_players: "لاعبين لا نهئيين,
            plan_free_nolimit: "لا حدود لعدد اللاعبين والبلوقنات",
            plan_free_online: "يعمل 24/7, لا طوابير",
            plan_dedicated_ports: "%s منافذ مخصصة",
            plan_online: "أونلاين",
            plan_custom_ports: "منافذ",
            plan_free_get: "تسجيل",
            plan_premium_get: "احصل علي الخطة المتميزة",
            plan_bungee_get: "احصل علي الحزمة",
            plan_custom_get: "احصل علي المخصصة",
            plan_free_support: "دعم فني رائع",
            plan_premium_support: "دعم فني مخصص",
            plan_bungee_support: "دعم فني ذو اولوية",
            features_title: "لماذا هو جميل جدا؟",
            features_subtitle: "لأننا كرسنا أنفسنا لنقدم لك الأفضل.",
            features_support_title: "دعم مباشر",
            features_support_subtitle: 'فريق الدعم لدينا متواجد على <a href="%s" class="text-white text-underline" target="_blank">سيرفر الديسكورد</a> لمساعدتك في أي وقت!',
            features_uptime_title: "يعمل 99% من الاوقات",
            features_uptime_subtitle: 'ولكن لا تأخذ كلامنا لذلك. تحقق بنفسك <a href="%s" class="text-white text-underline" target="_blank">من هنا</a>.',
            features_tech_title: "الرائدون في مجال التكنولوجية",
            features_tech_subtitle: "نعمل باستمرار على ترقية خدماتنا بحيث تكون خوادمك محدثة وبأسرع ما يمكن إنسانيًا.",
            features_title2: "متضمن مع جميع الخطط",
            features_subtitle2: "هذه هي الميزات والخصائص الأساسية لجميع خطط استضافة ماينكرافت التي نقدمها.",
            features_ddos_title: "حماية ضد هجمات DDoS",
            features_ddos_subtitle: "ونحن نستخدم وكلاء السبع طبقات العكسية لمقاومة هجمات رفض الخدمة الموزعة بسهولة.",
            features_disk_title: "NVMe SSD",
            features_disk_subtitle: "يعتمد الوقت الذي يستغرقه تشغيل الخادم على القرص مباشرة. لهذا السبب ذهبنا للأفضل.",
            features_scalability_title: "قابلية التوسع",
            features_scalability_subtitle: "تتيح لك لوحة التحكم لدينا ترقية خادمك ببضع نقرات في أي وقت تشاء. ابدأ بما تحتاجه وانتقل إلى قوة أكبر مع نمو للاعبينك.",
            features_panel_title: "لوحة تحكم Pterodactyl",
            features_panel_subtitle: "لم تكن إدارة الخوادم المتعددة أسهل من أي وقت مضى مع واجهة لوحة الويب Pterodactyl. الوصول مباشرة إلى ملفاتك ، ومحطة الخادم والمستخدمين الفرعيين.",
            features_sftp_title: "SFTP",
            features_sftp_description: "لا يتم تجاهل الأمان مطلقًا في MChost. يتيح لك بروتوكول نقل الملفات الآمن الذي قمنا بتطبيقه إدارة بياناتك من أي مكان ، بأمان.",
            features_scheduler_title: "جدول المهام",
            features_scheduler_subtitle: "نستخدم CRON للسماح لك بجدولة الأنشطة على الخادم الخاص بك مثل عمليات إعادة التشغيل العادية أو أي أمر آخر.",
            about_title: "معلومات عنا",
            about_subtitle: "نحن طموحون وملتزمون بتقديم أفضل وأعلى جودة ممكنة لخوادم الاستضافة الممكنة. لقد عملنا ليلًا ونهارًا لإعداد أفضل العقد الممكنة حتى تتمكن من الاستمتاع باللعب السلس والممتع مع أصدقائك على خادم ميانكرافت الخاص بك.",
            reviews_title: "المراجعات",
            reviews_subtitle: "لا تأخذ كلامنا كم هو عظيم. إليك ما يقوله عملاؤنا!",
            review1_title: "لن اكذب, هذه الإستضافة هي الافضل",
            review1_text: "هذه أفضل استضافة استعملتها. كما أن الأداء هو الأفضل ، حتى لو لم يكن خادمك يعمل بذاكرة RAM كبيرة.",
            review2_title: "إنها استضافة جيدة للغاية",
            review2_text: "الاستضافة جيدة جدا! لا لاج ، لا يوجد TPS تحت 19.9. انه لشيء رائع!",
            review3_title: "أفضل خدمة استضافة",
            review3_text: "هذه واحدة من أفضل خدمات الاستضافة التي واجهتها على الإطلاق وأنا سعيد لأنني وجدتها. لقد أنقذني بالتأكيد بضعة دولارات!",
            review4_title: "رائعة حقا",
            review4_text: "إنهم يعطونك SFTP ولوحة الويب. إنه ليس مثل الخدمات الأخرى التي تحد بشكل كبير من ما يمكنك القيام به. هذا كما لو أنك اشتريت خادمًا مناسبًا. أنا سعيد جدًا لأنني وجدت هذا.",
            panel_title: "يضم Pterodactyl",
            panel_subtitle: "Pterodactyl هي أفضل لوحة إدارة خادم ميانكرافت ، تم تصميمها مع وضع الأمان في الاعتبار ، فهي تدير جميع الخوادم في حاويات Docker المعزولة بينما تعرض واجهة مستخدم جميلة وبديهية.",
            need_support: 'لا تزال تبحث عن معلومات؟ <a href="%s">احصل على الدعم هنا</a> or join our <a href="%s" target="_blank">مجتمع الديسكورد</a>.',
            start_title: "ابدأ الخادم الخاص بك اليوم!",
            start_subtitle: "ماذا تنتظر؟ انه مجاني!",
            support_title: "دعم خبراء مباشر",
            support_subtitle: 'هل تحتاج إلى مساعدة فورية أو ترغب فقط في طرح بضعة أسئلة؟ <a href="https://discord.gg/Wx95Nx3" target="_blank">ادخل مجتمع الديسكورد الخاص بنا</a> والدردشة المباشرة مع وكيل الدعم. يمكنك أيضا مراسلتنا على البريد الإلكتروني <a href="mailto:support@mchost.cc">support@mchost.cc</a> في أي وقت تشاء.',
            footer_information: "معلومات",
            footer_pages: "صفحات",
            footer_more: "اكثر",
            footer_page_terms: "شروط الاستخدام",
            footer_page_privacy: "سياسة خاصة",
            footer_page_mc: "استضافة ميانكرافت",
            footer_page_pricing: "اسعار",
            footer_page_order: "طلب",
            footer_page_blog: "مدونة",
            footer_powered: "يعمل بواسطة",
            footer_copyright: "كل الحقوق محفوظة."
        },
        contact: {
            title: "تواصل معنا",
            field_name: "اسم",
            placeholder_name: "ضع اسمك هنا",
            field_organisation: "منظمة",
            placeholder_organisation: "ضع اسم منظمتك هنا",
            field_email: "البريد الإلكتروني",
            placeholder_email: "ضع بريدك الإلكتروني
            field_phone: "الهاتف",
            placeholder_phone: "ضع رقم الهاتف",
            field_message: "رسالة",
            placeholder_message: "رسالة من اجلنا",
            button_send: "ارسل الرسالة",
            note: '* هذه الحقول مطلوبة. بإرسالك فإنك توافق على <a href="%s" target="_blank">شروط الاستخدام</a>.'
        },
        hosting: {
            title: "خادم ميانكرافت",
            subtitle: "2GB RAM مجانا خادم ميانكرافت. مساحة تخزين NVMe SSD 100٪ ، على مدار 24 ساعة طوال أيام الأسبوع ، لا قوائم انتظار غبية ، لا حدود للاعب ، لا حدود للمكونات الإضافية ، أي إصدار ميانكرافت تريده! ابدأ الآن مجانًا!",
            plan_traffic: "مرور غير محدود",
            plan_ddos: "حماية الطبقة DDoS 7"
        },
        order: {
            title: "طلب",
            field_name: "اسم",
            placeholder_name: "ضع اسمك هنا",
            field_email: "البريد الالكتروني",
            placeholder_email: "ضع بريدك الالكتروني",
            field_pp_email: "البريد الالكتروني الخاص ببايبال",
            field_more: "تعليمات إضافية",
            button: "تقديم طلب",
            note: '* هذه الحقول مطلوبة. بإرسالك فإنك توافق على <a href="%s" target="_blank">شروط الاستخدام</a>.'
        },
        support: {
            title: "الدعم",
            subtitle: "يمكنك الوصول إلينا في أي مكان. إليك بعض الخيارات!",
            faq_title: "أسئلة مكررة",
            faq_text: "تحقق من قاعدة معارفنا قبل طرح سؤال. هناك فرصة أنه تم الرد عليك بالفعل.",
            dc_title: "دعم مباشر علي الديسكورد",
            dc_text: "انقر على الزر أدناه للانضمام إلى سيرفر الديسكورد الخاص بنا واطلب المساعدة.",
            email_title: "البريد الالكتروني",
            email_text: 'راسلنا عبر البريد الإلكتروني <a href="mailto:support@mchost.cc">support@mchost.cc</a> وسيتواصل معك أحد المندوبين خلال 12 ساعة!',
            form_title: "نموذج التواصل",
            form_text: "أو فقط أرسل لنا رسالة من خلال نموذج التواصل الخاص بنا."
        },
        arc_earn: {
            title: "كسب الأرصدة",
            subtitle: "يمكنك الحصول على أرصدة يمكن استخدامها لموارد إضافية عن طريق البقاء في الصفحة. ستحصل على رصيد واحد كل ساعة.",
            label: "يرجى إدخال أحد ما يلي",
            placeholder: "معرف الدسيكورد أو معرف العميل أو اسم مستخدم اللوحة",
            get_dc: "احصل على معرف الدسيكورد الخاص بك",
            get_panel: "احصل على اسم المستخدم الخاص بك",
            get_cid: "إحصل علي معرف العميل الخاص بك",
            unsure: 'لست متأكدًا من كيفية الحصول على أي من ذلك؟ <a href="$s" target="_blank">تواصل معنا</a>.',
            keep_open: "اترك هذه الصفحة مفتوحة لكسب الأرصدة!",
            earned: 'حصل على هذه الجلسة: <b class="credits">%s</b> أرصدة',
            btn_quit: "توقف",
            btn_refresh: "انعاش",
            btn_blank: "فارغ",
            text: 'أبقِ هذه الصفحة مفتوحة وستتلقى رصيدًا واحدًا كل ساعة. إذا أغلقت الصفحة ، فلديك 5 دقائق لفتحها مرة أخرى قبل إعادة تعيين الجلسة. إذا كنت ترغب في الحصول على المزيد من الاعتمادات لكل ساعة ، يرجى اتباع<a href="%s" target="_blank">هذا الشرح</a>.',
            video_subtitle: "يمكنك الحصول على أرصدة يمكن استخدامها لموارد إضافية من خلال مشاهدة إعلانات الفيديو بمكافأة.",
            short_title: "احصل على رصيد مجاني!",
            short_new: 'افتح عنوان URL هذا <a href="%s">%s</a> للحصول على مكافأة أخرى!',
            short_success: "لقد نجحت في المطالبة بمكافأتك!",
            short_error_title: "خطأ!",
            short_error_text: "تمت المطالبة بمكافأة هذه التجزئة بالفعل أو أنها غير موجودة.",
            short_error_new: 'عنوان URL لم تتم المطالبة به خصيصًا لك: <a href="%s">%s</a>'
        },
        gdpr: {
            text: "يستخدم موقعنا ملفات تعريف الارتباط. يرجى قراءة سياسة الخصوصية الخاصة بنا لمعرفة المزيد.",
            accept: "الموافقة",
            privacy: "سياسة الخصوصية"
        },
        dashboard: {
            welcome: "مرحبًا بك في لوحة التحكم!",
            btn_panel: "لوحة التحكم",
            btn_logout: "تسجيل خروج",
            servers: "خوادم",
            server_create: "إنشاء خادم",
            server_name: "إسم",
            server_actions: "أجراءات",
            server_unlimited: "غير محدود",
            balance: "MChost محفظة",
            balance_text: "الرصيد المتاح",
            balance_add: "إضافة",
            balance_store: "المتجر",
            balance_send: "إرسال",
            create_title: "إنشاء خادم",
            create_name: "اسم الخادم",
            create_quota: "حصة ذاكرة الوصول العشوائي المتبقية الخاصة بك هي %s مب",
            create_location: "موقعك",
            create_type: "نوع الخادم",
            create_btn: "إنشاء!",
            btn_close: "إغلاق",
            panel_title: "تسجيل الدخول إلى الوحة التحكم",
            panel_subtitle: "هذه هي بيانات الاعتماد الافتراضية التي يمكنك استخدامها لتسجيل الدخول إلى لوحة التحكم. يرجى ملاحظة أنه إذا قمت بتغييرها ، فلن يتم تحديثها هنا أيضًا.",
            panel_username: "اسم المستخدم",
            panel_pass: "كلمه السر",
            panel_show_pass: "عرض كلمة المرور",
            btn_login: "تسجيل الدخول",
            panel_open: "افتح اللوحة",
            add_title: "احصل على الرصيد",
            add_buy: "شراء أرصدة",
            add_buy_sub: "قم بتعبئة حسابك بالأرصدة باستخدام PayPal أو بطاقة ائتمان.",
            credits: "الرصيد",
            add_buy_buy: "التالى",
            add_giftcard: "استرداد بطاقة الهدايا",
            add_giftcard_sub: "استرد رمز MChost بطاقة الهداية للحصول على المزيد من الأرصدة!",
            gift_card: "كرت هدية",
            add_giftcard_btn: "إسترداد",
            add_idle: "البقاء",
            add_idle_sub: "يمكنك كسب أرصدة مجانية عن طريق الحفاظ على صفحتنا الخاملة مفتوحة في متصفحك.",
            add_idle_btn: "اذهب إلى وضع الخمول",
            add_app: "شاهد إعلان <small>(أندرويد)</small>",
            add_app_sub: "احصل على أرصدة مجانية لمشاهدة فيديو إعلاني على تطبيقنا للجوال.",
            add_app_btn: "تحميل",
            add_vid: "شاهد الإعلانات <small>(الكمبيوتر)</small>",
            add_vid_sub: "يمكنك أيضًا مشاهدة الإعلانات على متصفح جهاز الكمبيوتر الخاص بك لكسب أرصدة إضافية.",
            add_vid_btn: "شاهد",
            add_short: "عناوين URL قصيرة",
            add_short_sub: "انقر على الزر أدناه للحصول على أرصدة مجانية",
            add_short_btn: "إذهب",
            
        }
    }
}
