const translations = {
    ar: {
        home: {
            title: "استضافة ماينكرافت مجانية",
            subtitle: "الاستضافة هي مهنتنا؛ العملاء السعيد هم الأولوية. نحن نهدف إلى توفير خوادم ماينكرافت الأعلى جودة في السوق باستخدام أحدث التقنيات.",
            button_register: "تسجيل",
            button_dashboard: "لوحة التحكم",
            nav_contact: "التواصل",
            nav_panel: "لوحة التحكم",
            nav_dashboard: "منطقة العلماء",
            nav_button: "تسجيل",
            plans_title: "خططنا",
            plans_subtitle: "تستخدم جميع خوادم استضافة ماينكرافت تخزين SSD من الألف إلى الياء. مع MChost ، يمكنك الاستمتاع بزيادة الأداء والامتثال والتحكم الكامل في الخادم الخاص بك.",
            plan_free_title: "مجاني",
            plan_premium_title: "ممتاز",
            plan_bungee_title: "حزمة Bungee",
            plan_custom_title: "مخصصة",
            plan_free_plugins: "بلوقنات لا نهائية",
            plan_free_players: "لاعبين لا نهئيين,
            plan_free_nolimit: "لا حدود لعدد اللاعبين والبلوقنات",
            plan_free_online: "يعمل 24/7, لا طوابير",
            plan_dedicated_ports: "%s منافذ مخصصة",
            plan_online: "أونلاين",
            plan_custom_ports: "منافذ",
            plan_free_get: "تسجيل",
            plan_premium_get: "احصل علي الخطة المتميزة",
            plan_bungee_get: "احصل علي الحزمة",
            plan_custom_get: "احصل علي المخصصة",
            plan_free_support: "دعم فني رائع",
            plan_premium_support: "دعم فني مخصص",
            plan_bungee_support: "دعم فني ذو اولوية",
            features_title: "لماذا هو جميل جدا؟",
            features_subtitle: "لأننا كرسنا أنفسنا لنقدم لك الأفضل.",
            features_support_title: "دعم مباشر",
            features_support_subtitle: 'فريق الدعم لدينا متواجد على <a href="%s" class="text-white text-underline" target="_blank">سيرفر الديسكورد</a> لمساعدتك في أي وقت!',
            features_uptime_title: "يعمل 99% من الاوقات",
            features_uptime_subtitle: 'ولكن لا تأخذ كلامنا لذلك. تحقق بنفسك <a href="%s" class="text-white text-underline" target="_blank">من هنا</a>.',
            features_tech_title: "الرائدون في مجال التكنولوجية",
            features_tech_subtitle: "نعمل باستمرار على ترقية خدماتنا بحيث تكون خوادمك محدثة وبأسرع ما يمكن إنسانيًا.",
            features_title2: "متضمن مع جميع الخطط",
            features_subtitle2: "هذه هي الميزات والخصائص الأساسية لجميع خطط استضافة ماينكرافت التي نقدمها.",
            features_ddos_title: "حماية ضد هجمات DDoS",
            features_ddos_subtitle: "ونحن نستخدم وكلاء السبع طبقات العكسية لمقاومة هجمات رفض الخدمة الموزعة بسهولة.",
            features_disk_title: "NVMe SSD",
            features_disk_subtitle: "يعتمد الوقت الذي يستغرقه تشغيل الخادم على القرص مباشرة. لهذا السبب ذهبنا للأفضل.",
            features_scalability_title: "قابلية التوسع",
            features_scalability_subtitle: "تتيح لك لوحة التحكم لدينا ترقية خادمك ببضع نقرات في أي وقت تشاء. ابدأ بما تحتاجه وانتقل إلى قوة أكبر مع نمو للاعبينك.",
            features_panel_title: "لوحة تحكم Pterodactyl",
            features_panel_subtitle: "لم تكن إدارة الخوادم المتعددة أسهل من أي وقت مضى مع واجهة لوحة الويب Pterodactyl. الوصول مباشرة إلى ملفاتك ، ومحطة الخادم والمستخدمين الفرعيين.",
            features_sftp_title: "SFTP",
            features_sftp_description: "لا يتم تجاهل الأمان مطلقًا في MChost. يتيح لك بروتوكول نقل الملفات الآمن الذي قمنا بتطبيقه إدارة بياناتك من أي مكان ، بأمان.",
            features_scheduler_title: "جدول المهام",
            features_scheduler_subtitle: "نستخدم CRON للسماح لك بجدولة الأنشطة على الخادم الخاص بك مثل عمليات إعادة التشغيل العادية أو أي أمر آخر.",
            about_title: "معلومات عنا",
            about_subtitle: "نحن طموحون وملتزمون بتقديم أفضل وأعلى جودة ممكنة لخوادم الاستضافة الممكنة. لقد عملنا ليلًا ونهارًا لإعداد أفضل العقد الممكنة حتى تتمكن من الاستمتاع باللعب السلس والممتع مع أصدقائك على خادم ميانكرافت الخاص بك.",
            reviews_title: "المراجعات",
            reviews_subtitle: "لا تأخذ كلامنا كم هو عظيم. إليك ما يقوله عملاؤنا!",
            review1_title: "لن اكذب, هذه الإستضافة هي الافضل",
            review1_text: "هذه أفضل استضافة استعملتها. كما أن الأداء هو الأفضل ، حتى لو لم يكن خادمك يعمل بذاكرة RAM كبيرة.",
            review2_title: "إنها استضافة جيدة للغاية",
            review2_text: "الاستضافة جيدة جدا! لا لاج ، لا يوجد TPS تحت 19.9. انه لشيء رائع!",
            review3_title: "أفضل خدمة استضافة",
            review3_text: "هذه واحدة من أفضل خدمات الاستضافة التي واجهتها على الإطلاق وأنا سعيد لأنني وجدتها. لقد أنقذني بالتأكيد بضعة دولارات!",
            review4_title: "رائعة حقا",
            review4_text: "إنهم يعطونك SFTP ولوحة الويب. إنه ليس مثل الخدمات الأخرى التي تحد بشكل كبير من ما يمكنك القيام به. هذا كما لو أنك اشتريت خادمًا مناسبًا. أنا سعيد جدًا لأنني وجدت هذا.",
            panel_title: "يضم Pterodactyl",
            panel_subtitle: "Pterodactyl هي أفضل لوحة إدارة خادم ميانكرافت ، تم تصميمها مع وضع الأمان في الاعتبار ، فهي تدير جميع الخوادم في حاويات Docker المعزولة بينما تعرض واجهة مستخدم جميلة وبديهية.",
            need_support: 'لا تزال تبحث عن معلومات؟ <a href="%s">احصل على الدعم هنا</a> or join our <a href="%s" target="_blank">مجتمع الديسكورد</a>.',
            start_title: "ابدأ الخادم الخاص بك اليوم!",
            start_subtitle: "ماذا تنتظر؟ انه مجاني!",
            support_title: "دعم خبراء مباشر",
            support_subtitle: 'هل تحتاج إلى مساعدة فورية أو ترغب فقط في طرح بضعة أسئلة؟ <a href="https://discord.gg/Wx95Nx3" target="_blank">ادخل مجتمع الديسكورد الخاص بنا</a> والدردشة المباشرة مع وكيل الدعم. يمكنك أيضا مراسلتنا على البريد الإلكتروني <a href="mailto:support@mchost.cc">support@mchost.cc</a> في أي وقت تشاء.',
            footer_information: "معلومات",
            footer_pages: "صفحات",
            footer_more: "اكثر",
            footer_page_terms: "شروط الاستخدام",
            footer_page_privacy: "سياسة خاصة",
            footer_page_mc: "استضافة ميانكرافت",
            footer_page_pricing: "اسعار",
            footer_page_order: "طلب",
            footer_page_blog: "مدونة",
            footer_powered: "يعمل بواسطة",
            footer_copyright: "كل الحقوق محفوظة."
        },
        contact: {
            title: "تواصل معني",
            field_name: "اسم",
            placeholder_name: "ضع اسمك هنا",
            field_organisation: "منظمة",
            placeholder_organisation: "ضع اسم منظمتك هنا",
            field_email: "البريد الإلكتروني",
            placeholder_email: "ضع بريدك الإلكتروني
            field_phone: "الهاتف",
            placeholder_phone: "ضع رقم الهاتف",
            field_message: "رسالة",
            placeholder_message: "رسالة من اجلنا",
            button_send: "ارسل الرسالة",
            note: '* هذه الحقول مطلوبة. بإرسالك فإنك توافق على <a href="%s" target="_blank">شروط الاستخدام</a>.'
        },
        hosting: {
            title: "خادم ميانكرافت",
            subtitle: "2GB RAM مجانا خادم ميانكرافت. مساحة تخزين NVMe SSD 100٪ ، على مدار 24 ساعة طوال أيام الأسبوع ، لا قوائم انتظار غبية ، لا حدود للاعب ، لا حدود للمكونات الإضافية ، أي إصدار ميانكرافت تريده! ابدأ الآن مجانًا!",
            plan_traffic: "مرور غير محدود",
            plan_ddos: "حماية الطبقة DDoS 7"
        },
        order: {
            title: "Order",
            field_name: "Name",
            placeholder_name: "Please enter your name",
            field_email: "Email",
            placeholder_email: "Please enter your email",
            field_pp_email: "PayPal E-mail",
            field_more: "Additional Instructions",
            button: "Request Order",
            note: '* These fields are required. By submitting you agree to the <a href="%s" target="_blank">Terms of Use</a>.'
        },
        support: {
            title: "Support",
            subtitle: "You can reach us anywhere. Here are some options!",
            faq_title: "Frequently Asked Questions",
            faq_text: "Check out our knowledge base before asking a question. There's a chance it has already been answered for you.",
            dc_title: "Discord Live Support",
            dc_text: "Click the button below to join our Discord server and ask for help.",
            email_title: "E-mail",
            email_text: 'E-mail us at <a href="mailto:support@mchost.cc">support@mchost.cc</a> and a representative will get in touch with you within 12 hours!',
            form_title: "Contact form",
            form_text: "Or just send us a message through our contact form."
        },
        arc_earn: {
            title: "Earn Credits",
            subtitle: "You can get credits that can be used for extra resources by idling on a page. You will receive 1 credit every hour.",
            label: "PLEASE ENTER ONE OF THE FOLLOWING",
            placeholder: "Discord ID, Client ID or panel username",
            get_dc: "Get your Discord ID",
            get_panel: "Get your username",
            get_cid: "Get your Client ID",
            unsure: 'Not sure how to get any of that? <a href="$s" target="_blank">Contact us</a>.',
            keep_open: "Keep this page open to earn credits!",
            earned: 'Earned this session: <b class="credits">%s</b> credits',
            btn_quit: "Quit",
            btn_refresh: "Refresh",
            btn_blank: "Blank",
            text: 'Keep this page open and you will receive 1 credit every hour. If you close the page, you have 5 minutes to open it again before your session is reset. If you want to gain more credits per hour, please follow <a href="%s" target="_blank">this tutorial</a>.',
            video_subtitle: "You can get credits that can be used for extra resources by watching rewarded video ads.",
            short_title: "Get a credit for free!",
            short_new: 'Open this URL <a href="%s">%s</a> to get another reward!',
            short_success: "You have successfully claimed your reward!",
            short_error_title: "Error!",
            short_error_text: "The reward for this hash has already been claimed or it does not exist.",
            short_error_new: 'An unclaimed URL specially for you: <a href="%s">%s</a>'
        },
        gdpr: {
            text: "Our website is using cookies. Please read our Privacy Policy to find out more.",
            accept: "Accept",
            privacy: "Privacy Policy"
        },
        dashboard: {
            welcome: "Welcome to your dashboard!",
            btn_panel: "Control Panel",
            btn_logout: "Logout",
            servers: "Servers",
            server_create: "Create server",
            server_name: "Name",
            server_actions: "Actions",
            server_unlimited: "Unlimited",
            balance: "MChost Balance",
            balance_text: "Credits Available",
            balance_add: "Add",
            balance_store: "Store",
            balance_send: "Send",
            create_title: "Create Server",
            create_name: "Server Name",
            create_quota: "Your remaining RAM quota is %s MB",
            create_location: "Location",
            create_type: "Server rype",
            create_btn: "Create!",
            btn_close: "Close",
            panel_title: "Login to Panel",
            panel_subtitle: "These are your default credentials that you can use to log into the control panel. Please note if you change them, they will not update here as well.",
            panel_username: "Username",
            panel_pass: "Password",
            panel_show_pass: "Show password",
            btn_login: "Login",
            panel_open: "Open Panel",
            add_title: "Get Credits",
            add_buy: "Buy credits",
            add_buy_sub: "Top-up your account with credits using PayPal or a debit card.",
            credits: "Credits",
            add_buy_buy: "Next",
            add_giftcard: "Redeem Gift Card",
            add_giftcard_sub: "Redeem a MChost Gift Card code to get more credits!",
            gift_card: "Gift Card",
            add_giftcard_btn: "Redeem",
            add_idle: "Idling",
            add_idle_sub: "You can earn free credits by keeping our idling page open in your browser.",
            add_idle_btn: "Go idling",
            add_app: "Watch an ad <small>(Android)</small>",
            add_app_sub: "Get free credits for watching an advertisement video on our mobile app.",
            add_app_btn: "Download",
            add_vid: "Watch ads <small>(Desktop)</small>",
            add_vid_sub: "You can also watch ads on on your PC browser to earn extra credits.",
            add_vid_btn: "Watch",
            add_short: "Short URLs",
            add_short_sub: "Click the button below to get free credits",
            add_short_btn: "Go",
            
        }
    }
}
